repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
- repo: local
  hooks:
  - id: terraform-fmt
    name: Форматирование terraform
    description: Отформатировать файлы terraform
    entry: terraform fmt
    language: system
    files: '.(tf|tfvars)$'
